Repository DanggeunPlanner/danggeun-planner-BE, pull requests merged in 2023-01, with the labels that each got.

#9 🔧 Chore : ResponseMessage 기초 작업
  src/main/java/com/finalteam4/danggeunplanner/common/response/ResponseMessage.java
Labels: new feature

#16 ✨ Feat: CD 구축
  .github/workflows/deploy.yml
Labels: new feature

#13 ✨ Feat : CI 구축
  .github/workflows/gradle.yml
Labels: new feature

#17 ✨ Feat : CD 구축
  appspec.yml
  build.gradle
  build.gradle.kts
  scripts/start.sh
  scripts/stop.sh
Labels: new feature

#15 ✨ Feat : 단순 회원가입 기능 구현 Feature/signup(#3)
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberSignUpRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/entity/Member.java
  src/main/java/com/finalteam4/danggeunplanner/member/repository/MemberRepository.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
Labels: new feature

#29 ✨ Feat : 로그인 기능 구현 및 시큐리티 추가
  build.gradle
  src/main/java/com/finalteam4/danggeunplanner/common/exception/ErrorCode.java
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberLogInRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberLogInResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/entity/Member.java
  src/main/java/com/finalteam4/danggeunplanner/member/repository/MemberRepository.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
  src/main/java/com/finalteam4/danggeunplanner/security/UserDetailsImpl.java
  src/main/java/com/finalteam4/danggeunplanner/security/UserDetailsServiceImpl.java
  src/main/java/com/finalteam4/danggeunplanner/security/config/WebSecurityConfig.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtAuthFilter.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtUtil.java
  src/main/resources/application.properties
Labels: new feature

#34 🐛 Fix : Cors 설정 변경
  src/main/java/com/finalteam4/danggeunplanner/security/config/WebSecurityConfig.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtAuthFilter.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtUtil.java
Labels: bug

#39 ✨ Feat : 회원 검색 기능 구현
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberInfoResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/entity/Member.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
Labels: new feature

#43 ✨ Feat : 그룹 등록 기능 구현
  build.gradle
  src/main/java/com/finalteam4/danggeunplanner/group/controller/GroupController.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/request/GroupInfoRequest.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/GroupInfoResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/entity/Group.java
  src/main/java/com/finalteam4/danggeunplanner/group/entity/GroupImageEnum.java
  src/main/java/com/finalteam4/danggeunplanner/group/entity/Participant.java
  src/main/java/com/finalteam4/danggeunplanner/group/service/GroupService.java
Labels: new feature

#45 ✨ Feat : 프로필 이미지 변경 기능 구현
  build.gradle
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/entity/Member.java
  src/main/java/com/finalteam4/danggeunplanner/security/config/WebSecurityConfig.java
  src/main/java/com/finalteam4/danggeunplanner/storage/config/S3Config.java
  src/main/java/com/finalteam4/danggeunplanner/storage/controller/ProfileImageController.java
  src/main/java/com/finalteam4/danggeunplanner/storage/dto/ProfileImageResponse.java
  src/main/java/com/finalteam4/danggeunplanner/storage/service/ProfileImageService.java
  src/main/java/com/finalteam4/danggeunplanner/storage/service/S3UploaderService.java
  src/main/resources/application.properties
Labels: new feature

#46 ✨ Feat : 그룹 수정,삭제 기능 구현
  src/main/java/com/finalteam4/danggeunplanner/common/exception/ErrorCode.java
  src/main/java/com/finalteam4/danggeunplanner/group/controller/GroupController.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/GroupListResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/entity/Group.java
  src/main/java/com/finalteam4/danggeunplanner/group/participant/entity/Participant.java
  src/main/java/com/finalteam4/danggeunplanner/group/participant/repository/ParticipantRepository.java
  src/main/java/com/finalteam4/danggeunplanner/group/service/GroupService.java
Labels: new feature

#49 🐛 Fix : 회원 검색 로직 수정 및 코드 리팩토링
  build.gradle
  src/main/java/com/finalteam4/danggeunplanner/DanggeunplannerApplication.java
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberLoginRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberSignUpRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberUpdateUsernameRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberInfoListResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberUpdateUsernameResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/entity/Member.java
  src/main/java/com/finalteam4/danggeunplanner/member/repository/MemberRepository.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
  src/main/resources/application.properties
Labels: refactor

#57 ✨ Feat : refreshToken 기능 추가
  src/main/java/com/finalteam4/danggeunplanner/common/exception/ErrorCode.java
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/entity/Member.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
  src/main/java/com/finalteam4/danggeunplanner/security/config/WebSecurityConfig.java
  src/main/java/com/finalteam4/danggeunplanner/security/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtAuthFilter.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtUtil.java
Labels: new feature

#62 ♻ Refactor : 그룹 전체 리펙토링
  src/main/java/com/finalteam4/danggeunplanner/group/dto/request/GroupInfoRequest.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/GroupDetailResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/GroupInfoResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/GroupListResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/ParticipantRankingResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/entity/Group.java
  src/main/java/com/finalteam4/danggeunplanner/group/repository/GroupRepository.java
  src/main/java/com/finalteam4/danggeunplanner/group/service/GroupService.java
  src/main/java/com/finalteam4/danggeunplanner/group/service/GroupValidator.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
Labels: refactor

#65 ♻ Refactor : 전체적인 코드 리팩토링
  src/main/java/com/finalteam4/danggeunplanner/common/exception/ErrorCode.java
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberAuthRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberInfoRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberLoginRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberLoginResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberProfileImageResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberValidator.java
  src/main/java/com/finalteam4/danggeunplanner/security/config/WebSecurityConfig.java
  src/main/java/com/finalteam4/danggeunplanner/storage/controller/ProfileImageController.java
  src/main/java/com/finalteam4/danggeunplanner/storage/service/ProfileImageService.java
  src/main/java/com/finalteam4/danggeunplanner/timer/repository/TimerRepository.java
Labels: refactor

#66 🐛 Fix : refreshToken 에러 수정
  src/main/java/com/finalteam4/danggeunplanner/common/exception/ErrorCode.java
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberAuthRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberUpdateUsernameRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/repository/MemberRepository.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
  src/main/java/com/finalteam4/danggeunplanner/security/config/WebSecurityConfig.java
  src/main/java/com/finalteam4/danggeunplanner/security/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtAuthFilter.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtUtil.java
Labels: bug

#68 ✨ Feat : 그룹원 조회, 탈퇴 기능 구현
  src/main/java/com/finalteam4/danggeunplanner/common/exception/ErrorCode.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/GroupDetailResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/GroupListResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/ParticipantRankingResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/entity/Group.java
  src/main/java/com/finalteam4/danggeunplanner/group/service/GroupService.java
  src/main/java/com/finalteam4/danggeunplanner/group/service/GroupValidator.java
  src/main/java/com/finalteam4/danggeunplanner/invitation/service/InvitationService.java
  src/main/java/com/finalteam4/danggeunplanner/participant/controller/ParticipantController.java
  src/main/java/com/finalteam4/danggeunplanner/participant/dto/response/ParticipantInfoResponse.java
  src/main/java/com/finalteam4/danggeunplanner/participant/dto/response/ParticipantListResponse.java
  src/main/java/com/finalteam4/danggeunplanner/participant/entity/Participant.java
  src/main/java/com/finalteam4/danggeunplanner/participant/repository/ParticipantRepository.java
  src/main/java/com/finalteam4/danggeunplanner/participant/service/ParticipantService.java
  src/main/java/com/finalteam4/danggeunplanner/participant/service/ParticipantValidator.java
  src/main/java/com/finalteam4/danggeunplanner/timer/repository/TimerRepository.java
Labels: new feature

#75 ✨ Feat : 그룹원 초대 기능 구현
  src/main/java/com/finalteam4/danggeunplanner/group/controller/GroupController.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/request/GroupInvitationRequest.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/GroupInvitationResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/GroupSearchMemberResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/response/GroupSearchResponse.java
  src/main/java/com/finalteam4/danggeunplanner/group/service/GroupService.java
  src/main/java/com/finalteam4/danggeunplanner/invitation/controller/InvitationController.java
  src/main/java/com/finalteam4/danggeunplanner/invitation/dto/response/InvitationListResponse.java
  src/main/java/com/finalteam4/danggeunplanner/invitation/dto/response/InvitationResponse.java
  src/main/java/com/finalteam4/danggeunplanner/invitation/entity/Invitation.java
  src/main/java/com/finalteam4/danggeunplanner/invitation/repository/InvitationRepository.java
  src/main/java/com/finalteam4/danggeunplanner/invitation/service/InvitationService.java
  src/main/java/com/finalteam4/danggeunplanner/invitation/service/InvitationValidator.java
  src/main/java/com/finalteam4/danggeunplanner/participant/repository/ParticipantRepository.java
Labels: new feature

#76 ✨ Feat : 카카오 로그인 기능 추가 및 회원 검색 코드 수정
  build.gradle
  src/main/java/com/finalteam4/danggeunplanner/common/exception/ErrorCode.java
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/OauthLoginRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/entity/Member.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberValidator.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/OauthService.java
  src/main/java/com/finalteam4/danggeunplanner/security/config/WebSecurityConfig.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtAuthFilter.java
Labels: bug, new feature, refactor

#77 ♻ Refactor : 토큰 재발행 관련 사용하지 않는 코드 제거
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtAuthFilter.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtUtil.java
Labels: refactor

#79 ♻ Refactor : participant 코드 수정
  src/main/java/com/finalteam4/danggeunplanner/group/entity/GroupImageEnum.java
  src/main/java/com/finalteam4/danggeunplanner/group/service/GroupService.java
  src/main/java/com/finalteam4/danggeunplanner/member/repository/MemberRepository.java
  src/main/java/com/finalteam4/danggeunplanner/participant/repository/ParticipantRepository.java
  src/main/java/com/finalteam4/danggeunplanner/participant/service/ParticipantService.java
Labels: refactor

#82 ♻ Refactor : 전체 코드 Valid 리펙토링
  src/main/java/com/finalteam4/danggeunplanner/common/exception/GlobalExceptionHandler.java
  src/main/java/com/finalteam4/danggeunplanner/common/exception/ValidationGroups.java
  src/main/java/com/finalteam4/danggeunplanner/common/exception/ValidationSequence.java
  src/main/java/com/finalteam4/danggeunplanner/group/controller/GroupController.java
  src/main/java/com/finalteam4/danggeunplanner/group/dto/request/GroupInfoRequest.java
  src/main/java/com/finalteam4/danggeunplanner/group/service/GroupService.java
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberAuthRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberUpdateUsernameRequest.java
  src/main/java/com/finalteam4/danggeunplanner/participant/service/ParticipantService.java
  src/main/java/com/finalteam4/danggeunplanner/planner/controller/PlanController.java
  src/main/java/com/finalteam4/danggeunplanner/planner/dto/request/PlanRequest.java
  src/main/java/com/finalteam4/danggeunplanner/planner/repository/PlannerRepository.java
  src/main/java/com/finalteam4/danggeunplanner/timer/controller/TimerController.java
  src/main/java/com/finalteam4/danggeunplanner/timer/dto/request/TimerFinishRequest.java
  src/main/java/com/finalteam4/danggeunplanner/timer/dto/request/TimerStartRequest.java
  src/main/java/com/finalteam4/danggeunplanner/timer/dto/request/TimerUpdateRequest.java
Labels: refactor

#87 ✨ Feat : 레디스 적용하여 리프레시토큰 로직 수정
  build.gradle
  src/main/java/com/finalteam4/danggeunplanner/common/exception/ErrorCode.java
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberDisclosureRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberLogoutResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberMyPageResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/entity/Member.java
  src/main/java/com/finalteam4/danggeunplanner/member/repository/MemberRepository.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
  src/main/java/com/finalteam4/danggeunplanner/participant/service/ParticipantService.java
  src/main/java/com/finalteam4/danggeunplanner/redis/config/RedisConfig.java
  src/main/java/com/finalteam4/danggeunplanner/redis/service/RedisService.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtAuthFilter.java
  src/main/java/com/finalteam4/danggeunplanner/security/jwt/JwtUtil.java
  src/main/resources/application.properties
Labels: new feature

#91 ♻ Refactor : 그룹 참가자 리스트 정렬 순서 변경
  src/main/java/com/finalteam4/danggeunplanner/member/controller/MemberController.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberDisclosureResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberMyPageResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/response/MemberUpdateUsernameResponse.java
  src/main/java/com/finalteam4/danggeunplanner/member/entity/Member.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/MemberService.java
  src/main/java/com/finalteam4/danggeunplanner/member/service/OauthService.java
  src/main/java/com/finalteam4/danggeunplanner/participant/dto/response/ParticipantInfoResponse.java
  src/main/java/com/finalteam4/danggeunplanner/participant/service/ParticipantService.java
  src/main/java/com/finalteam4/danggeunplanner/participant/service/ParticipantValidator.java
Labels: refactor

#95 🐛 Fix : 테스트 중 코드 수정
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/MemberAuthRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/dto/request/OauthLoginRequest.java
  src/main/java/com/finalteam4/danggeunplanner/member/entity/Member.java
  src/main/java/com/finalteam4/danggeunplanner/notification/service/NotificationService.java
  src/main/java/com/finalteam4/danggeunplanner/security/config/WebSecurityConfig.java
Labels: refactor
